#!/bin/bash
TERM=linux
file="/var/run/python-script.pid" #the file where you keep your string name
pid=`cat $file`        #the output of cat $file is assigned to the $name variable
echo "running"
if ps -p $pid > /dev/null
then
   echo "$pid is running"
   # Do something knowing the pid exists, i.e. the process with $PID is running
   exit
else
   echo $pid "is not running"
   /usr/bin/env python /home/sidereal_time/new_code.py 2> /etc/code_error.txt &
fi

exit
