#!/bin/bash
sudo gpio -g mode 24 out
sudo gpio -g write 24 1
sleep 1
sudo gpio -g write 24 0
sleep 1
sudo gpio -g write 24 1
sleep 1
sudo gpio -g write 24 0
sleep 1
sudo gpio -g write 24 1
sleep 1
sudo gpio -g write 24 0
sleep 1
sudo gpio -g write 24 1
sleep 1
sudo gpio -g write 24 0
sleep 1
sudo gpio -g write 24 1
sleep 1
sudo gpio -g write 24 0

exit
