#!/bin/bash
cd /home/time_for_pi/menu
command="/usr/bin/python /home/time_for_pi/menu/noon_fire.py 2> /etc/noon_error.txt"
job="59 11 * * * sleep 10 ; $command"
cat <(fgrep -i -v "$command" <(crontab -l)) <(echo "$job") | crontab -

